### ISSUE TITLE
[travis] Missing Esplora-Liquid image in deploy step  

### ISSUE THREAD

**Issue by tiero** [vulpemventures/docker-esplora#3]

**Comment by altafan** [comment]
Since we decided to use the development server instead of building the dist release, we do not have 2 different images of esplora anymore ([commit](https://github.com/vulpemventures/docker-esplora/commit/5842836627e9900401e3c774700f3fb40ffc1fab)).

The reason behind having 2 different images was because we were builidng esplora and thus we needed to set the `API_URL` env var when building the docker image through a build argument.

Now that we use the dev server we do not need a docker build argument anymore and we're free to set the `API_URL` variable as an environment variable. This is the reason why I removed the `ARG` from the Dockerfile and I suspect that this could be the reason why we were failing to customize the api url from Nigiri for our public regtest.

PS. You can also see that in the [compose](https://github.com/vulpemventures/nigiri/blob/master/resources/docker-compose-regtest-liquid.yml#L110) file of Nigiri we already use `vulpemventures/esplora:latest` for both the Liquid and the Bitcoin explorer.

**Comment by altafan** [comment]
Closing.
